#!/bin/bash
module load nvhpc/20.9/netcdf-fortran/4.5.3 nvhpc/20.9/netcdf-c/4.7.4-mpi compilers/nvhpc-20.9-mpi

thread=2

export OMP_NUM_THREADS=$thread

srun -A hackathon -p batch -N 1 -c $thread --gres=gpu:1 -t 0:30:00  ./exec.omp/fyppm.x
