#!/bin/bash
module load nvhpc/20.9/netcdf-fortran/4.5.3 nvhpc/20.9/netcdf-c/4.7.4-mpi compilers/nvhpc-20.9-mpi

# 1: turn on OPENACC diagnosis
export PGI_ACC_TIME=0

# cpu thread
thread=1
#srun -N 1 --ntasks=$thread -p batch -t 00:02:00 ./exec.acc/c_sw.x
srun -N 1 --ntasks=$thread -p batch -t 00:02:00 --gres=gpu:$thread ./exec.acc/c_sw.x
#srun -N 1 --ntasks=$thread -p batch -t 00:02:00 --gres=gpu:$thread nsys profile --force-overwrite true -o csw.qdrep ./exec.acc/c_sw.x
